version: '3.8'

services:
  app:
    build: .
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    volumes:
      - .:/app                  # dev only; remove in prod
      - cookies-vol:/cookies    # shared volume for cookies
      - ./downloads:/app/downloads
    environment:
      FLASK_ENV: development
    command: python3 app.py
    ports:
      - "5005:5005"
    restart: unless-stopped

  cleaner:
    build: .
    volumes:
      - ./downloads:/app/downloads
    command: python3 cleanup.py
    restart: on-failure

  cookie_refresher:
    build:
      context: ./cookie_refresher
      dockerfile: Dockerfile
    volumes:
      - cookies-vol:/cookies
    command: python /app/refresh_cookies.py
    restart: "no"
    # In Coolify, schedule this as a cron job (e.g. 0 3 * * 0)

volumes:
  cookies-vol:
 